In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [5]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
# 第1個3是資料的筆數
x = tf.ones((3, 3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.16772208, -0.02599969, -0.29369888, -0.04423258],
       [-0.16772208, -0.02599969, -0.29369888, -0.04423258],
       [-0.16772208, -0.02599969, -0.29369888, -0.04423258]],
      dtype=float32)>

In [4]:
# 另一種寫法
# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.24651119,  0.37315363, -0.12026483,  0.6474434 ],
       [ 0.24651119,  0.37315363, -0.12026483,  0.6474434 ],
       [ 0.24651119,  0.37315363, -0.12026483,  0.6474434 ]],
      dtype=float32)>

In [6]:
# 另一種寫法
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu"))
model.add(layers.Dense(3, activation="relu"))
model.add(layers.Dense(4))

# Call layers on a test input
x = tf.ones((3, 3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.7475553, -1.9164262,  1.1443222,  0.8574941],
       [-1.7475553, -1.9164262,  1.1443222,  0.8574941],
       [-1.7475553, -1.9164262,  1.1443222,  0.8574941]], dtype=float32)>

In [18]:
model.layers[1].name

'dense_16'

In [19]:
model.pop()
print(len(model.layers))  # 2

2


In [20]:
model.layers[1].weights 

[<tf.Variable 'sequential_10/dense_16/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.78405154, -1.0826526 ,  0.7553756 ],
        [ 0.97416663, -0.7147891 ,  0.86055946]], dtype=float32)>,
 <tf.Variable 'sequential_10/dense_16/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [21]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             multiple                  8         
_________________________________________________________________
dense_16 (Dense)             multiple                  9         
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 另一種寫法
# input_shape
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))

model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [24]:
# 另一種寫法
# keras.Input(shape=(250, 250, 3))
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# Can you guess what the current output shape is at this point? Probably not.
# Let's just print it:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 121, 121, 32)      9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 40, 40, 32)        0         
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


In [27]:
# feature_extractor, 無dense
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features[0]

<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
array([[[[0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         ...,
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066]],

        [[0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         [0.18154085, 0.        , 0.        , ..., 0.        ,
          0.35662112, 0.29714066],
         ...,
         [0.18154085, 0.     

In [28]:
# only extract features from one layer
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)
# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features[0]

<tf.Tensor: shape=(121, 121, 32), dtype=float32, numpy=
array([[[0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        ...,
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502]],

       [[0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        [0.05839239, 0.        , 0.        , ..., 0.33867472,
         0.        , 0.10355502],
        ...,
        [0.05839239, 0.        , 0.        , ..., 0.

In [0]:
# Freeze all layers except the last one.
for layer in model.layers[:-1]:
    layer.trainable = False


In [30]:
# Load a convolutional base with pre-trained weights
base_model = keras.applications.Xception(
    weights='imagenet',
    include_top=False,
    pooling='avg')

# Freeze the base model
base_model.trainable = False

# Use a Sequential model to add a trainable classifier on top
model = keras.Sequential([
    base_model,
    layers.Dense(1000),
])

# # Compile & train
# model.compile(...)
# model.fit(...)

83689472/83683744 [==============================] - 1s 0us/step
